In [2]:
%load_ext autoreload
%autoreload 2
notebook_fixed_dir = False

In [3]:
# this cell can only be called once
import os
if not notebook_fixed_dir:
    os.chdir('..')
    notebook_fixed_dir = True
print(os.getcwd())

/home/svcl-oowl/brandon/research/sil_consistent_at_inference


In [7]:
import pickle
import pprint
import glob

import trimesh
import torch
import pandas as pd
from tqdm.autonotebook import tqdm
from PIL import Image
import numpy as np
from pytorch3d.io import save_obj

from utils import utils, eval_utils
from evaluation import compute_iou_2d, compute_iou_2d_given_pose, compute_iou_3d, compute_chamfer_L1
from utils.visualization_tools import show_refinement_results
from utils.brute_force_pose_est import brute_force_estimate_pose

In [36]:
mesh_original_path = os.path.join("notebooks/test.obj")
device = torch.device("cuda:0")
with torch.no_grad():
    mesh_original = utils.load_untextured_mesh(mesh_original_path, device)
resized_verts_slow = torch.tensor(eval_utils.normalize_pointclouds_numpy_all_axes_slow(mesh_original.verts_packed().cpu().numpy()))
resized_verts_fast = torch.tensor(eval_utils.normalize_pointclouds_numpy_all_axes(mesh_original.verts_packed().cpu().numpy()))
print(resized_verts_slow)
print(resized_verts_fast)
print(torch.allclose(resized_verts_slow, resized_verts_fast))
#print(torch.max(mesh_original.verts_packed(), 0))
#print(torch.min(mesh_original.verts_packed(), 0))
#print(torch.max(resized_verts, 0))
#print(torch.min(resized_verts, 0))
#save_obj("notebooks/test_resized.obj", resized_verts, mesh_resized.faces_packed())

tensor([[-1.0000, -0.9814,  0.8959],
        [-0.9976, -0.9819, -0.9055],
        [-0.9959, -0.9810,  0.9377],
        ...,
        [ 0.9652, -0.9815,  0.8690],
        [ 0.9212, -0.9025,  0.9065],
        [ 1.0000, -0.9823,  0.9088]])
tensor([[-1.0000, -0.9814,  0.8959],
        [-0.9976, -0.9819, -0.9055],
        [-0.9959, -0.9810,  0.9377],
        ...,
        [ 0.9652, -0.9815,  0.8690],
        [ 0.9212, -0.9025,  0.9065],
        [ 1.0000, -0.9823,  0.9088]])
True


In [28]:
x = np.array([-3, -2, -1, 1,2,3,4,5])
print(x)
x[x>0] = np.array([44,55,66,77,88])
print(x)
#x[np.array([1,4])] = np.array([99, 94])
#print(x)

[-3 -2 -1  1  2  3  4  5]
[-3 -2 -1 44 55 66 77 88]
